name = "gestionale-server"
compatibility_date = "2024-03-01"

[vars]
# Add and environment variables here
CORS_ORIGIN = "https://gestionale-ets.pages.dev"
#JWT_SECRET= "G0tLflHRh7GykKVRCAOEVxP7Ba8bvEvp"

[[d1_databases]]
binding = "DB"
database_name = "gestionale-ets-db"
database_id = "4df11d70-8eea-4f4f-bca4-63a26c8dfc59"
migrations_dir = "drizzle/migrations"
remote = true

[observability]
enabled = true

